name: tictactoe
description: A simple dart project to play a very basic version of tictactoe
version: 0.0.1
#homepage: https://github.com/Chickenpowerrr
#author: Chickenpowerrr

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
